# Development Stage
FROM node:22 AS dev

WORKDIR /frontend

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install

# Copy the source code
COPY . ./

# Start the development server
EXPOSE 5173
CMD ["npm", "run", "dev"]

