FROM python:3.13

WORKDIR /backend

# Copy requirements.txt and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app
COPY . ./

# Expose port 8000
EXPOSE 8000

# Start the server
CMD ["uvicorn", "main:app", "--port", "8000"]
